Add -Wno-deprecated-declarations to libdng_sdk
This fixes building with Mac OS SDK >= 13.

Without this flag, the following error occurs:

    error: 'sprintf' is deprecated: This function is provided for compatibility
reasons only.  Due to security concerns inherent in the design of sprintf(3),
it is highly recommended that you use snprintf(3) instead.
[-Werror,-Wdeprecated-declarations]

Change-Id: I918c8d8409e7cbb7425529ffe13463a0c23ff742